-- Importación inicial de precios de Xofly Nails & Spa.
-- No sobrescribe registros existentes. Ejecutar una sola vez o repetir sin duplicar.
-- Si ya existe la prueba inicial, se deja intacta como registro separado.
BEGIN;
INSERT INTO public.xofly_services (name,category,price,description,active) SELECT 'Limpieza facial profunda · 1 sesión', 'Catálogo · Faciales', 700, 'Precio de catálogo inicial', true WHERE NOT EXISTS (SELECT 1 FROM public.xofly_services WHERE name='Limpieza facial profunda · 1 sesión' AND category='Catálogo · Faciales');
INSERT INTO public.xofly_services (name,category,price,description,active) SELECT 'Limpieza facial profunda · 3 sesiones', 'Catálogo · Faciales', 1900, 'Precio de catálogo inicial', true WHERE NOT EXISTS (SELECT 1 FROM public.xofly_services WHERE name='Limpieza facial profunda · 3 sesiones' AND category='Catálogo · Faciales');
INSERT INTO public.xofly_services (name,category,price,description,active) SELECT 'Limpieza facial profunda · 5 sesiones', 'Catálogo · Faciales', 3100, 'Precio de catálogo inicial', true WHERE NOT EXISTS (SELECT 1 FROM public.xofly_services WHERE name='Limpieza facial profunda · 5 sesiones' AND category='Catálogo · Faciales');
INSERT INTO public.xofly_services (name,category,price,description,active) SELECT 'Limpieza facial profunda · anual (12)', 'Catálogo · Faciales', 7080, 'Precio de catálogo inicial', true WHERE NOT EXISTS (SELECT 1 FROM public.xofly_services WHERE name='Limpieza facial profunda · anual (12)' AND category='Catálogo · Faciales');
INSERT INTO public.xofly_services (name,category,price,description,active) SELECT 'Despigmentante facial/corporal · 1 zona', 'Catálogo · Faciales', 950, 'Precio de catálogo inicial', true WHERE NOT EXISTS (SELECT 1 FROM public.xofly_services WHERE name='Despigmentante facial/corporal · 1 zona' AND category='Catálogo · Faciales');
INSERT INTO public.xofly_services (name,category,price,description,active) SELECT 'Despigmentante · 4 sesiones', 'Catálogo · Faciales', 3200, 'Precio de catálogo inicial', true WHERE NOT EXISTS (SELECT 1 FROM public.xofly_services WHERE name='Despigmentante · 4 sesiones' AND category='Catálogo · Faciales');
INSERT INTO public.xofly_services (name,category,price,description,active) SELECT 'Antienvejecimiento · 1 sesión', 'Catálogo · Faciales', 1100, 'Precio de catálogo inicial', true WHERE NOT EXISTS (SELECT 1 FROM public.xofly_services WHERE name='Antienvejecimiento · 1 sesión' AND category='Catálogo · Faciales');
INSERT INTO public.xofly_services (name,category,price,description,active) SELECT 'Antienvejecimiento · 4 sesiones', 'Catálogo · Faciales', 3600, 'Precio de catálogo inicial', true WHERE NOT EXISTS (SELECT 1 FROM public.xofly_services WHERE name='Antienvejecimiento · 4 sesiones' AND category='Catálogo · Faciales');
INSERT INTO public.xofly_services (name,category,price,description,active) SELECT 'Reducción de papada · 4 sesiones', 'Catálogo · Faciales', 3200, 'Precio de catálogo inicial', true WHERE NOT EXISTS (SELECT 1 FROM public.xofly_services WHERE name='Reducción de papada · 4 sesiones' AND category='Catálogo · Faciales');
INSERT INTO public.xofly_services (name,category,price,description,active) SELECT 'Reductivo abdomen · 6 sesiones', 'Catálogo · Corporal', 4200, 'Precio de catálogo inicial', true WHERE NOT EXISTS (SELECT 1 FROM public.xofly_services WHERE name='Reductivo abdomen · 6 sesiones' AND category='Catálogo · Corporal');
INSERT INTO public.xofly_services (name,category,price,description,active) SELECT 'Reductivo brazos · 6 sesiones', 'Catálogo · Corporal', 2200, 'Precio de catálogo inicial', true WHERE NOT EXISTS (SELECT 1 FROM public.xofly_services WHERE name='Reductivo brazos · 6 sesiones' AND category='Catálogo · Corporal');
INSERT INTO public.xofly_services (name,category,price,description,active) SELECT 'Anticelulitis piernas · 6 sesiones', 'Catálogo · Corporal', 3200, 'Precio de catálogo inicial', true WHERE NOT EXISTS (SELECT 1 FROM public.xofly_services WHERE name='Anticelulitis piernas · 6 sesiones' AND category='Catálogo · Corporal');
INSERT INTO public.xofly_services (name,category,price,description,active) SELECT 'Levantamiento senos o glúteos · 6 sesiones', 'Catálogo · Corporal', 4100, 'Precio de catálogo inicial', true WHERE NOT EXISTS (SELECT 1 FROM public.xofly_services WHERE name='Levantamiento senos o glúteos · 6 sesiones' AND category='Catálogo · Corporal');
INSERT INTO public.xofly_services (name,category,price,description,active) SELECT 'Sesión por zona con aparatología', 'Catálogo · Corporal', 800, 'Precio de catálogo inicial', true WHERE NOT EXISTS (SELECT 1 FROM public.xofly_services WHERE name='Sesión por zona con aparatología' AND category='Catálogo · Corporal');
INSERT INTO public.xofly_services (name,category,price,description,active) SELECT 'Sesión por zona sencilla', 'Catálogo · Corporal', 600, 'Precio de catálogo inicial', true WHERE NOT EXISTS (SELECT 1 FROM public.xofly_services WHERE name='Sesión por zona sencilla' AND category='Catálogo · Corporal');
INSERT INTO public.xofly_services (name,category,price,description,active) SELECT 'Drenaje linfático completo', 'Catálogo · Masajes', 1200, 'Precio de catálogo inicial', true WHERE NOT EXISTS (SELECT 1 FROM public.xofly_services WHERE name='Drenaje linfático completo' AND category='Catálogo · Masajes');
INSERT INTO public.xofly_services (name,category,price,description,active) SELECT 'Descarga muscular · una zona', 'Catálogo · Masajes', 450, 'Precio de catálogo inicial', true WHERE NOT EXISTS (SELECT 1 FROM public.xofly_services WHERE name='Descarga muscular · una zona' AND category='Catálogo · Masajes');
INSERT INTO public.xofly_services (name,category,price,description,active) SELECT 'Masaje relajante completo · 45 min', 'Catálogo · Masajes', 800, 'Precio de catálogo inicial', true WHERE NOT EXISTS (SELECT 1 FROM public.xofly_services WHERE name='Masaje relajante completo · 45 min' AND category='Catálogo · Masajes');
INSERT INTO public.xofly_services (name,category,price,description,active) SELECT 'Masaje relajante medio cuerpo · 30 min', 'Catálogo · Masajes', 350, 'Precio de catálogo inicial', true WHERE NOT EXISTS (SELECT 1 FROM public.xofly_services WHERE name='Masaje relajante medio cuerpo · 30 min' AND category='Catálogo · Masajes');
INSERT INTO public.xofly_services (name,category,price,description,active) SELECT 'Masaje cráneo-facial · 30 min', 'Catálogo · Faciales', 300, 'Precio de catálogo inicial', true WHERE NOT EXISTS (SELECT 1 FROM public.xofly_services WHERE name='Masaje cráneo-facial · 30 min' AND category='Catálogo · Faciales');
INSERT INTO public.xofly_services (name,category,price,description,active) SELECT 'Auriculoterapia', 'Catálogo · Auriculoterapia', 500, 'Precio de catálogo inicial', true WHERE NOT EXISTS (SELECT 1 FROM public.xofly_services WHERE name='Auriculoterapia' AND category='Catálogo · Auriculoterapia');
INSERT INTO public.xofly_services (name,category,price,description,active) SELECT 'Auriculoterapia · 1 aplicación', 'Catálogo · Auriculoterapia', 450, 'Precio de catálogo inicial', true WHERE NOT EXISTS (SELECT 1 FROM public.xofly_services WHERE name='Auriculoterapia · 1 aplicación' AND category='Catálogo · Auriculoterapia');
INSERT INTO public.xofly_services (name,category,price,description,active) SELECT 'Auriculoterapia · 2 aplicaciones', 'Catálogo · Auriculoterapia', 800, 'Precio de catálogo inicial', true WHERE NOT EXISTS (SELECT 1 FROM public.xofly_services WHERE name='Auriculoterapia · 2 aplicaciones' AND category='Catálogo · Auriculoterapia');
INSERT INTO public.xofly_services (name,category,price,description,active) SELECT 'Auriculoterapia · 4 aplicaciones', 'Catálogo · Auriculoterapia', 1200, 'Precio de catálogo inicial', true WHERE NOT EXISTS (SELECT 1 FROM public.xofly_services WHERE name='Auriculoterapia · 4 aplicaciones' AND category='Catálogo · Auriculoterapia');
COMMIT;
